### ISSUE TITLE
Critical Section is completely broken

### ISSUE THREAD

**Issue by Codetector1374** [ch32-rs/qingke#3]
The critical section implementation seems to be having both typo and fundamental design flaws.

1. The `gintenr::write` is actually performing an atomic [Code Here](https://github.com/ch32-rs/qingke/blob/3ca273ed3044a14cefb95b7449b9279c7e0e08a5/src/register/gintenr.rs#L20) bitwise OR with the value and `gintenr`, instead of writing it with `csrrw` which result in the interrupt actually never getting masked. [see the use here](https://github.com/ch32-rs/qingke/blob/3ca273ed3044a14cefb95b7449b9279c7e0e08a5/src/critical_section_impl.rs#L11)
2. The interface of the `gintenr::set_disable` makes it impossible to implement a sound / nest-able critical section by masking interrupt. What needed is that `set_disable` **atomically** set and return the old value of the `gintenr` CSR. [Critical Section Impl](https://github.com/ch32-rs/qingke/blob/3ca273ed3044a14cefb95b7449b9279c7e0e08a5/src/critical_section_impl.rs#L8) I hope this is obvious that there is a TOCTOU problem.

Also just to note that the whole embassy runtime currently works **because** this critical section is a NOP. With it "fixed" the `wfi` in the embassy runner's main loop would actually get stuck in the wfi forever.
[Executor code](https://github.com/embassy-rs/embassy/blob/bc0180800d751e651c0d15c807285c11cdb4f486/embassy-executor/src/arch/riscv32.rs#L72)

**Comment by andelf** [comment]
Thank you for reporting this issue.

I'm currently on holiday, but I'll investigate and address this bug as soon as I return. In the meantime, if anyone would like to contribute a fix, pull requests are certainly welcome.
